name: release
"on":
  workflow_dispatch:
    inputs: {}
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
      - run: npm install
      - run: npm run build
      - run: npm install -g vsce
      - run: vsce package
      - uses: softprops/action-gh-release@v1
        with:
          files: vscode-content-converter-extension-*.vsix
